---
title: "Chapter 7"
author: "Darian-Florian Voda"
date: "2023-05-20"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Data Visualization
### A practical Introduction
#### By Kieran Healy

```{r}
library(gapminder)
library(tidyverse)
library(ggplot2)
library(socviz)
library(ggrepel)
library(scales)
library(dplyr)
```

```{r}
election %>% select(state, total_vote, r_points, pct_trump, party, census) %>%
  sample_n(5)
```

```{r}
# Hex color codes for Dem Blue and Rep Red
party_colors = c("#2E74C0", "#CB454A")

p0 = ggplot(data = subset(election, st %nin% "DC"),
            mapping = aes(x = r_points,
                          y = reorder(state, r_points),
                          color = party))

p1 = p0 + geom_vline(xintercept = 0, color = "gray30") + geom_point(size = 2)

p2 = p1 + scale_color_manual(values = party_colors)

p3 = p2 + scale_x_continuous(breaks = c(-30, -20, -10, 0, 10, 20, 30, 40),
                             labels = c("30\n (Clinton", "20", "10", "0", "10", "20", "30", "40\n (Trump)"))

p3 + facet_wrap(~ census, ncol = 1, scales = "free_y") +
  guides(color = FALSE) + labs(x = "Point Margin", y = "") +
  theme(axis.text = element_text(size=8))
```

```{r}
# Hex color codes for Dem Blue and Rep Red
party_colors = c("#2E74C0", "#CB454A")

p0 = ggplot(data = subset(election, st %nin% "DC"),
            mapping = aes(x = r_points,
                          y = reorder(state, r_points),
                          color = party))

p1 = p0 + geom_vline(xintercept = 0, color = "gray30") + geom_point(size = 2)

p2 = p1 + scale_color_manual(values = party_colors)

p3 = p2 + scale_x_continuous(breaks = c(-30, -20, -10, 0, 10, 20, 30, 40),
                             labels = c("30\n (Clinton", "20", "10", "0", "10", "20", "30", "40\n (Trump)"))

p3 + facet_wrap(~ census, ncol = 1) +
  guides(color = FALSE) + labs(x = "Point Margin", y = "") +
  theme(axis.text = element_text(size=8))
```

```{r}
# Hex color codes for Dem Blue and Rep Red
party_colors = c("#2E74C0", "#CB454A")

p0 = ggplot(data = subset(election, st %nin% "DC"),
            mapping = aes(x = r_points,
                          y = reorder(state, r_points),
                          color = party))

p1 = p0 + geom_vline(xintercept = 0, color = "gray30") + geom_point(size = 2)

p2 = p1

p3 = p2 + scale_x_continuous(breaks = c(-30, -20, -10, 0, 10, 20, 30, 40),
                             labels = c("30\n (Clinton", "20", "10", "0", "10", "20", "30", "40\n (Trump)"))

p3 + facet_wrap(~ census, ncol = 1, scales = "free_y") +
  guides(color = FALSE) + labs(x = "Point Margin", y = "") +
  theme(axis.text = element_text(size=8))
```

```{r}
library(maps)
us_states = map_data("state")
head(us_states)
```

```{r}
dim(us_states)
```

```{r}
p = ggplot(data = us_states, mapping = aes(x = long, y = lat, group=group))

p + geom_polygon(fill = "white", color = "black")
```

```{r}
p = ggplot(data = us_states, mapping = aes(x = long, y = lat, group=group, fill = region))

p + geom_polygon(color = "gray90", size = 0.1) + guides(fill = FALSE)
```

## Question: What is the difference between Mercator and Albers projection?

```{r}
p = ggplot(data = us_states,
           mapping = aes(x = long, y = lat, group = group, fill = region))

p + geom_polygon(color = "gray90", size = 0.1) + 
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  guides(fill = FALSE)
```

```{r}
election$region = tolower(election$state)
us_states_elec = left_join(us_states, election)
```

```{r}
p = ggplot(data = us_states_elec,
           aes(x = long, y = lat, group = group, fill = party))

p + geom_polygon(color = "gray90", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45)
```

```{r}
library(ggthemes)
p0 = ggplot(data = us_states_elec,
           aes(x = long, y = lat, group = group, fill = party))

p1 = p + geom_polygon(color = "gray90", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45)

p2 = p1 + scale_fill_manual(values = party_colors) + labs(title = "Election Results 2016", fill = NULL)
p2 + theme_map()
```

```{r}
p0 = ggplot(data = us_states_elec,
           aes(x = long, y = lat, group = group, fill = pct_trump))

p1 = p + geom_polygon(color = "gray90", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45)

p1 + labs(title = "Trump vote") + theme_map() + labs(fill = "Percent")
```


## Question: Here i got an error, why?
```{r}
p0 = ggplot(data = us_states_elec,
           aes(x = long, y = lat, group = group, fill = d_points))

p1 = p + geom_polygon(color = "gray90", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45)

p2 = p1 + scale_fill_gradient2() + labs(title = "Winning margins")
p2 + theme_map() + labs(fill = "Percent")

p3 = p1 + scale_fill_gradient2(low = "red", mid = scales::muted("purple"),
                               high = "blue", breaks=c(-25,0,25,50,75)) +
  labs(title="Winning margins")
p3 + theme_map() + labs(fill = "Percent")
```

```{r}
county_map %>% sample_n(5)
```

```{r}
county_data %>%
  select(id, name, state, pop_dens, pct_black) %>%
  sample_n(5)
```

```{r}
county_full = left_join(county_map, county_data, by = "id")
```

```{r}
p = ggplot(data = county_full,
           mapping = aes(x = long, y = lat,
                         fill = pop_dens,
                         group = group))

p1 = p + geom_polygon(color = "gray90", size = 0.05) + coord_equal()

p2 = p1 + scale_fill_brewer(palette = "Blues",
                            labels = c("0-10", "10-50", "50-100", "100-500", "500-1,000", "1,000-5,000", ">5,000"))

p2 + labs(fill = "Population per\nsquare mile")+
  theme_map() +
  guides(fill = guide_legend(nrow = 1)) +
  theme(legend.position = "bottom")
```

```{r}
p = ggplot(data = county_full,
           mapping = aes(x = long, y = lat,
                         fill = pop_dens,
                         group = group))

p1 = p + geom_polygon(color = "gray90", size = 0.05) + coord_equal()
p2 = p1 + scale_fill_brewer(palette = "Greens")
p2
```