---
title: "Chapter 8"
author: "Darian-Florian Voda"
date: "2023-05-06"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Data Visualization
### A practical Introduction
#### By Kieran Healy

```{r}
library(gapminder)
library(tidyverse)
library(ggplot2)
library(socviz)
library(ggrepel)
library(scales)
library(dplyr)
```

```{r}
head(asasec)
```

```{r}
p = ggplot(data = subset(asasec, Year == 2014), mapping = aes(x = Members, y = Revenues, label = Sname))

p + geom_point() + geom_smooth()
```

```{r}
p = ggplot(data = subset(asasec, Year == 2014), mapping = aes(x = Members, y = Revenues, label = Sname))

p + geom_point(mapping = aes(color = Journal)) + geom_smooth(method="lm")
```

```{r}
p0 = ggplot(data = subset(asasec, Year == 2014), mapping = aes(x = Members, y = Revenues, label = Sname))

p1 = p0 + geom_smooth(method = "lm", se = FALSE, color = "gray80") + geom_point(mapping = aes(color = Journal))

p2 = p1 + geom_text_repel(data = subset(asasec, Year == 2014 & Revenues > 7000), size = 2)
p2
```

```{r}
p3 = p2 + labs(x = "Membership", y="Revenues", color = "Section has own Journal", title = "ASA Sections",
               subtitle = "2014 Calendar year.", caption = "Source: ASA annual report.")

p4 = p3 + scale_y_continuous(labels = scales::dollar) + theme(legend.position = "bottom")

p4
```

## Question: What is Likert scale?

```{r}
p = ggplot(data = organdata, mapping = aes(x = roads, y = donors, color = world))

p + geom_point(size = 2) + scale_color_brewer(palette = "Set2") + theme(legend.position = "top")
```

```{r}
demo('colors')
```

```{r}
# Democrat Blue and Republican Red

party_colors = c("#2E74C0", "#CB454A")

p0 = ggplot(data = subset(county_data, flipped = "No"),
            mapping = aes(x = pop, y = black/100))

p1 = p0 + geom_point(alpha = 0.15, color = "gray50") + scale_x_log10(labels = scales::comma)

p1
```

```{r}
p2 = p1 + geom_point(data = subset(county_data, flipped == "Yes"),
                     mapping = aes(x=pop, y = black/100, color = partywinner16)) +
  scale_color_manual(values = party_colors)

p2
```

```{r}
p3 = p2 + scale_y_continuous(labels=scales::percent)+
  labs(color = "County flipped to ...",
       x = "County Population (log scale)",
       y = "Percent Black Population",
       title = "Flipped counties, 2016",
       caption = "Counties in gray did not flip.")

p3

```

## Question: What does gather() do??

```{r}

```